apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: polymetrie
spec:
  rules:
    - host: polymetrie.example.com  # Remplacez "votrehote.com" par votre h√¥te
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polymetrie-increment-service
                port:
                  number: 5000

